### ISSUE TITLE
R argument switching mutants are equivalent

### ISSUE THREAD

**Issue by tdhock** [agroce/universalmutator#26]
hi @agroce 
I'm trying to make PRs based on the R data.table mutants https://github.com/Rdatatable/data.table/issues/6114

And I noticed that many of the mutants involve switching the order of arguments, here are two examples.

[setops.R:8](https://github.com/Rdatatable/data.table/blob/1.15.0/R/setops.R#L8) by.y becomes cols in either case.
```
by.y = colnamesInt(y, by.y, check_dups=TRUE)
by.y = colnamesInt(y, check_dups=TRUE, by.y)
```

[transpose.R:63](https://github.com/Rdatatable/data.table/blob/1.15.0/R/transpose.R#L63) type.convert becomes x in either case.
```
indxs = unlist(type.convert, recursive=FALSE, use.names=FALSE)
indxs = unlist( recursive=FALSE,type.convert, use.names=FALSE)
```

All of these argument switching mutants in R code are equivalent, because R first matches the named arguments, then assigns the positional arguments.

For future mutation testing of R code, it would be useful to avoid generating such mutants, perhaps by adding a rule that if the argument to switch has an equals sign (name=value, so it is a named argument), then do not try switching.

**Comment by agroce** [comment]
@debsourav33 @kjain14 you guys are the rule hacking experts now; is this hard?  It'd actually be better for Python too, since swapping named args is always equivalent

**Comment by debsourav33** [comment]
Shouldn't be very hard to achieve.. Just need to find a clever way to skip the arguments with '=' in it.. I will try updating the rules and make a PR

**Comment by tdhock** [comment]
perhaps an alternative to turning it off would be switching values or names in two named arguments
```r
fun(x=1, y=2)
fun(x=2, y=1)
```
etc

**Comment by debsourav33** [comment]
Addressed both issues (skip swapping named arguments and swap their values/names instead) in the PR https://github.com/agroce/universalmutator/pull/27

**Comment by agroce** [comment]
Closed via #27

**Comment by tdhock** [comment]
yay thanks

**Comment by agroce** [comment]
@tdhock not on pip yet, though, note
