### ISSUE TITLE
Unsupported on Windows

### ISSUE THREAD

**Issue by vallant** [agroce/universalmutator#3]
Hello,
thanks for your work on this great mutation framework. 
I just noticed one small issue, it seems like it isn't supported on windows yet because of a python-subprocess call to `diff`. Do you think that its possible to just use the python-native solution [https://docs.python.org/3/library/difflib.html](difflib)?

Thanks, Stephan

**Comment by agroce** [comment]
Should work on windows now; I switched to difflib, also found a bug in the coverage checking that could show up in the old code, should be fixed now.  Thanks for bringing this to my attention (I think the difflib output is a little nicer in some cases, anyway)!

**Comment by vallant** [comment]
Awesome, thanks for the quick fix!
