### ISSUE TITLE
Is there a way to obtain the current mutant-source-filename in the command passed to analyze_mutants?

### ISSUE THREAD

**Issue by vallant** [agroce/universalmutator#4]
Hello, i'm currently using `universalmutator` in a C++ project. 
I've generated the mutant sources using the `mutate` command and am using `analyze_mutants` not to actually analyze the mutants, but to compile them in order to use them later in evaluation. 
So the command passed to `analyze_mutants` is just compiling the binary and moving it to a different location under a different name. I want the output name to reflect the mutated source file that was actually used: Say my program is called `foo` and the mutated source file is `bar.cpp`, then this is what i want to achieve:
`bar.0.cpp -> foo.bar.0.exe, bar.1.cpp -> foo.bar.1.exe` 
and so on. 
Currently i'm using a workaround, where the compile-command counts the lines in the `notkilled.txt` and `killed.txt` (that were generated by `analyze_mutants`). If using the `--noShuffle` option, this line count represents the index of the mutant source that is currently being used- this way i know which mutant source is currently being processed. 

Now while this approach is working, its not the most elegant way of handling this i guess.
What if the `analyze_mutants` would just set an environment variable, e.g. `CURRENT_MUTANT_SOURCE` before it calls the compile-command? This way the compile command is very easily aware of which source file it is currently processing. 

All the best, Stephan

**Comment by agroce** [comment]
@valiant I just saw this issue, not much traffic here and my notifications are not on for some reason!

This is a good idea, and I'll implement it in a reasonable time frame!  Sorry for the delay!

**Comment by agroce** [comment]
Er, @vallant

**Comment by agroce** [comment]
I think it should be a pretty easy tweak, too, as you say I know the name obviously, so just set an envvar, I'll have to make sure it's properly passed to the subshell that runs the command, but shouldn't be hard.

**Comment by agroce** [comment]
Haven't updated pip yet, but a fix should be in place now.  Let me know if it works, I'll update pip soon.

**Comment by vallant** [comment]
Nice, thank you very much!

**Comment by agroce** [comment]
I actually committed the wrong version of the code there, was trying something out; please grab the latest github (or, shortly, pip)
