### ISSUE TITLE
Problems with genmutants.py

### ISSUE THREAD

**Issue by JiyangZhang** [agroce/universalmutator#5]
Hi, 

thanks for developing this tool, it is very useful!

I found a bug in genmutants.py https://github.com/agroce/universalmutator/blob/4c0110dd742f7f24e4b29b9982a5f19c9f1554b4/universalmutator/genmutants.py#L190

Here the map object needs to be converted to list object to make sure it can be iterated.

**Comment by agroce** [comment]
Good catch!
