### ISSUE TITLE
prioritize_mutants fails when invoked with only statement deletion mutants

### ISSUE THREAD

**Issue by kjain14** [agroce/universalmutator#8]
prioritize_mutants fails in the case when there are only statement deletion mutants to choose from. For example, take this file notkilled.txt with mutant: CasbinPolicyFileNotFoundException.mutant.0.java. If the mutant CasbinPolicyFileNotFoundException.mutant.0.java is a statement deletion mutants the following block of code invoked by prioritize_mutants will fail:

sdmutants = []
if not noSDPriority:
    print("IDENTIFYING STATEMENT DELETION MUTANTS")
    sdmutants = list(filter(utils.isStatementDeletion, mutants))
    for m in sdmutants:
        mutants.remove(m)
    print("PRIORITIZING", len(sdmutants), "STATEMENT DELETIONS")
    if len(sdmutants) > 0:
        ranking = utils.FPF(sdmutants, N, cutoff=cutoff, verbose=verbose)
        with open(outfile, 'w') as outf:
            for (m, r) in ranking:
                mname = m[0]
                outf.write(mname + "\n")
    print()
else:
    with open(outfile, 'w') as outf:
        pass

print("PRIORITIZING", int(N) - len(sdmutants), "MUTANTS")

ranking = utils.FPF(mutants, N - len(sdmutants), cutoff=cutoff, verbose=verbose, avoid=sdmutants)

Specifically, on the first call to ranking, it will rank the statement deletion mutant. But since it removes the statement deletion mutant from mutants, on the second call to ranking utils.FPF will be invoked with an empty list. This causes the following snippet to fail in FPF:

if f is None:
    ranking = [(mlist[0], -1)]

I think the fix to this is not making the second call to utils.FPF when mutants is empty.

**Comment by agroce** [comment]
Grab from github, should be fixed now.  I'll update pip later today
